#include "emulator/compiletime/cWriter.h"
#include "shared/platform.h"
#include <string.h>
#include <stdio.h>
#include <stdarg.h>
#include <stdlib.h>

static uint32_t headerHash(void* value) {
    cHeader* str = value;
    uint32_t hash = 2166126261u;

    for(size_t i = 0; i < strlen(str->fileName); i++) {
        hash ^= str->fileName[i];
        hash *= 16777619;
    }

    return hash;
}

static bool headerCmp(void* a, void* b) {
    cHeader* tokA = a;
    cHeader* tokB = b;

    return strcmp(tokA->fileName, tokB->fileName) == 0;
}

static uint32_t varHash(void* value) {
    cVariable* str = value;
    uint32_t hash = 2166126261u;

    for(size_t i = 0; i < strlen(str->name); i++) {
        hash ^= str->name[i];
        hash *= 16777619;
    }

    return hash;
}

static bool varCmp(void* a, void* b) {
    cVariable* tokA = a;
    cVariable* tokB = b;

    return strcmp(tokA->name, tokB->name) == 0;
}

void initWriter(cWriter* writer) {
    writer->preamble = NULL;
    initTable(&writer->headers, headerHash, headerCmp);
    initTable(&writer->variables, varHash, varCmp);
    ARRAY_ALLOC(char*, *writer, initCode);
    writer->footer = NULL;
}

void addHeader(cWriter* writer, const char* header, bool system) {
    cHeader* head = ArenaAlloc(sizeof(cHeader));
    head->fileName = header;
    head->system = system;

    tableSet(&writer->headers, head, (void*)1);
}

void addVariable(cWriter* writer, const char* type, const char* name) {
    cVariable* var = ArenaAlloc(sizeof(cVariable));
    var->name = name;
    var->type = type;

    if(!tableSet(&writer->variables, var, (void*)1)) {
        cErrPrintf(TextRed, "Duplicate VM variables: %s\n", name);
        exit(1);
    }
}

void addInitCode(cWriter* writer, const char* format, ...) {
    va_list args;
    va_start(args, format);

    size_t bufSize = vsnprintf(NULL, 0, format, args);
    char* buf = ArenaAlloc(sizeof(char) * (bufSize + 1));
    vsnprintf(buf, bufSize, format, args);

    PUSH_ARRAY(char*, *writer, initCode, buf);

    va_end(args);
}

void writeC(const char* fileName, cWriter* writer) {
    FILE* file = fopen(fileName, "w");

    fputs("// Autogenerated by microasm generate\n", file);

    for(unsigned int i = 0; i < writer->headers.capacity; i++) {
        Entry* entry = &writer->headers.entries[i];
        if(entry->key.value == NULL) {
            continue;
        }
        cHeader* head = entry->key.value;
        if(head->system) {
            fputs("#include <", file);
            fputs(head->fileName, file);
            fputs(">\n", file);
        } else {
            fputs("#include \"", file);
            fputs(head->fileName, file);
            fputs("\"\n", file);
        }
    }

    if(writer->preamble) {
        fputs(writer->preamble, file);
    }

    for(unsigned int i = 0; i < writer->variables.capacity; i++) {
        Entry* entry = &writer->variables.entries[i];
        if(entry->key.value == NULL) {
            continue;
        }
        cVariable* var = entry->key.value;
        fputs(var->type, file);
        fputs(" ", file);
        fputs(var->name, file);
        fputs(";\n", file);
    }

    for(unsigned int i = 0; i < writer->initCodeCount; i++) {
        fputs(writer->initCodes[i], file);
        fputs("\n", file);
    }

    if(writer->footer) {
        fputs(writer->footer, file);
    }

    fclose(file);
}