#include "emulator/compiletime/cWriter.h"
#include <stdio.h>

void initWriter(cWriter* writer) {
    ARRAY_ALLOC(const char*, *writer, header);
}

void addHeader(cWriter* writer, const char* header, bool system) {
    cHeader head;
    head.fileName = header;
    head.system = system;

    PUSH_ARRAY(cHeader, *writer, header, head);
}

void writeC(const char* fileName, cWriter* writer) {
    FILE* file = fopen(fileName, "w");

    fputs("// Autogenerated by microasm generate\n", file);

    for(unsigned int i = 0; i < writer->headerCount; i++) {
        cHeader* head = &writer->headers[i];
        if(head->system) {
            fputs("#include <", file);
            fputs(head->fileName, file);
            fputs(">\n", file);
        } else {
            fputs("#include \"", file);
            fputs(head->fileName, file);
            fputs("\"\n", file);
        }
    }

    fputs(writer->preamble, file);

    fclose(file);
}