// Autogenerated File: Do not modify, all changes will be overwritten 

#include "emulator/vmcore.c"
int main(int argc, char** argv) {
Register ARegister;
Register BRegister;
Bus addressBus;
Bus dataBus;
}