#include <math.h>
#include <string.h>
#include <stdio.h>

#include "shared/platform.h"
#include "shared/memory.h"
#include "microcode/codegen.h"

void codegen(Microcode* m, char* outputFile) {
    char* filename;
    const char* dot = strrchr(outputFile, '.');
    const char* slash = strrchr(outputFile, '/');
    bool bsErr = false;
    if(pathSeperator[0] == '\\') {
        const char* backslash = strrchr(outputFile, '\\');
        bsErr = backslash > dot;
    }
    if(dot == NULL || slash > dot || bsErr) {
        size_t len = strlen(outputFile) + 7;
        filename = ArenaAlloc(sizeof(char) * len);
        strncpy(filename, outputFile, len - 7);
        strcat(filename, ".uasmb");
        filename[len - 1] = '\0';
    } else {
        filename = outputFile;
    }
    cOutPrintf(TextWhite, "CodeGen: Opcode[%u]->%s\n", m->opcodeCount, filename);
    for(unsigned int i = 0; i < m->opcodeCount; i++) {
        cOutPrintf(TextWhite, "  code %u\n", m->opcodes[i].id);
    }

    FILE* file = fopen(filename, "wb+");
    fputs(
        "// Autogenerated File: Do not modify, all changes will be overwritten \n\n"
        "#include \"emulator/vmcore.h\"\n"
        "void emulator() {\n}"
    , file);
    fclose(file);
}