name: CI

on: [push, pull_request]

jobs:
  build-ubuntu:
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Debug
    - name: build
      run: |
        cd build
        make

  build-windows:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: |
        mkdir build
        cd build
        cmake .. -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" -DCMAKE_BUILD_TYPE=Debug
    - name: build
      run: |
        cd build
        mingw32-make
